# Generated by Django 3.2.19 on 2023-06-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='eircode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
