# Generated by Django 3.2.19 on 2023-06-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230627_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonelog',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.client'),
        ),
    ]
