# Generated by Django 3.2.19 on 2023-07-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='county',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
