# Generated by Django 3.2.19 on 2023-07-05 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_clientnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.client'),
        ),
    ]
