# Generated by Django 3.2.19 on 2023-07-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_clientnote_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientnote',
            old_name='Content',
            new_name='content',
        ),
    ]
