# Generated by Django 3.2.19 on 2023-07-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
