# Generated by Django 3.2.19 on 2023-07-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_todolist_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_a_client', models.BooleanField(default=False)),
                ('app_start', models.DateTimeField(auto_now_add=True)),
                ('app_end', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('app_note', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.client')),
            ],
        ),
    ]
