# Generated by Django 3.2.19 on 2023-07-21 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_appointment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='app_end',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='app_start',
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('10 AM', '10AM'), ('11 AM', '11 AM'), ('12 PM', '12PM'), ('2 PM', '2 PM'), ('3 PM', '3PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM')], default='', max_length=5),
        ),
    ]
